server:
  port: 9010
spring:
  application:
    name: parseExcel
  web:
    resources:
      static-locations: classpath:/static/
    # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: lh123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# MyBatis配置
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#---------自定义配置-----------
#生成kettle脚本配置
kettle:
  output:
    path: ~/Documents/ISPR/kettle_file/售后/售后保修/
#文件工具类配置
file:
  source-path: /Users/huanliu/Documents/tempfile/video
  target-path: /Users/huanliu/Documents/tempfile/audio
#图片本地存储路径
image:
  path: D:/tmp/media/image/
  #使用占位符填充为当前ip地址
  prefix-url: http://#{T(java.net.InetAddress).getLocalHost().getHostAddress()}/media/image/

