server:
  port: 9010
spring:
  application:
    name: parseExcel
  web:
    resources:
      static-locations: classpath:/static/
logging:
  level:
    org:
      springframework: error
    com:
      example:
        mapper: debug
#生成kettle脚本配置
kettle:
  output: ~/Documents/ISPR/kettle_file



