server:
  port: 9010
spring:
  application:
    name: parseExcel
  web:
    resources:
      static-locations: classpath:/static/
logging:
  level:
    org:
      springframework: error
    com:
      example:
        mapper: debug



